FROM alpine:3.12 AS base

FROM base AS builder 

RUN apk add --no-cache luarocks5.1 gcc musl-dev openssl-dev lua5.1-dev \
        && luarocks-5.1 install lapis

FROM base as final

EXPOSE 80

RUN echo "http://openresty.org/package/alpine/v3.12/main" >> /etc/apk/repositories \
	&& wget 'http://openresty.org/package/admin@openresty.com-5ea678a6.rsa.pub' -O /etc/apk/keys/admin@openresty.com-5ea678a6.rsa.pub \
	&& apk add --no-cache lua5.1 lua5.1-inspect lua5.1-sql-mysql openresty

COPY lua-ms/ /opt/app/

COPY --from=builder /usr/share/lua /usr/share/lua
COPY --from=builder /usr/local/share/lua /usr/local/share/lua
COPY --from=builder /usr/local/lib/lua /usr/local/lib/lua
COPY --from=builder /usr/local/bin/lapis /usr/local/bin/

COPY lua-lapis/docker/alpine3.12/nginx.conf /usr/local/openresty/nginx/conf/nginx.conf

WORKDIR /opt/app

CMD /usr/local/openresty/nginx/sbin/nginx -g 'daemon off; master_process on;'

