clair:
  database:
    # Database driver
    type: pgsql
    options:
      source: host=clairdb port=5432 user=postgres password=password sslmode=disable statement_timeout=60000
      cachesize: 16384
      paginationkey:
      maxopenconnections: 10
  api:
    addr: "0.0.0.0:6060"
    healthaddr: "0.0.0.0:6061"
    timeout: 900s

  updater:
    interval: 2h

  notifier:
    attempts: 3
    renotifyinterval: 2h
