version: '3.6'

services:
  clair: 
    image: quay.io/coreos/clair:latest
    ports:
    - "6060:6060"
    volumes: 
    - type: bind
      source: ./config.yaml 
      target: /config/config.yaml
    restart: on-failure
    depends_on: 
    - clairdb 
    command: -config=/config/config.yaml

  clairdb:
    image: arminc/clair-db:latest
